name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test CI scheme
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        env:
          scheme: CI
          workspace: Marvel.xcworkspace
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -workspace $workspace CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 11"
      - name: Test
        env:
          scheme: CI
          workspace: Marvel.xcworkspace
        run: |
          xcodebuild test-without-building -scheme "$scheme" -workspace $workspace CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO -enableCodeCoverage YES -destination "platform=iOS Simulator,name=iPhone 11"
